This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file D:/Personal Folder/Teza/Git/Thesis/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (676 entries accepted, 0 rejected).
Sorting entries.........done (7767 comparisons).
Generating output file thesis.acr....done (256 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
